#!/bin/sh
mytitle="Software Tool V2.0"
echo -e '\033]2;'$mytitle'\007'
username=$(whoami)
ver="1.0"
if [ -n "$(command -v lsb_release)" ]; then
	distro=$(lsb_release -s -d)
elif [ -f "/etc/os-release" ]; then
	distro=$(grep PRETTY_NAME /etc/os-release | sed 's/PRETTY_NAME=//g' | tr -d '="')
fi
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Software Tool" | lolcat
figlet -t -f ~/.fonts/cybersmall.flf "By VNux Team" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Xin chao ban $username!           "
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("Trinh_quan_ly_goi" "Phan_mem_da_phuong_tien"  "Phan_mem_Internet" "Phan_mem_sua_anh" "Phan_mem_sua_van_ban" "Giao_dien" "Quan_ly_giao_dien" "Nhan_Linux" "Thoat")
select opt in ${option[*]};
do
case $opt in

"Quan_ly_giao_dien")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Desktop Manager" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat nhan nao?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("LightDM" "LXDM" "SDDM" "GDM" "XDM" "Thoat")
select opt in ${option[*]};
do
case $opt in

"Thoat")
clear
break;;

"XDM")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S xorg-xdm xdm-archlinux --noconfirm
echo
echo
echo "Xong!"

break;;

"GDM")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S gdm --noconfirm
echo
echo
echo "Xong!"

break;;

"SDDM")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S sddm  --noconfirm
echo
echo
echo "Xong!"

break;;

"LXDM")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S lxdm-gtk3  --noconfirm
echo
echo
echo "Xong!"

break;;

"LightDM")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S lightdm lightdm-gtk-greeter  --noconfirm
echo
echo
echo "Xong!"

break;;


esac
done
break;;

"Nhan_Linux")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Kernels" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat nhan nao?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("Linux" "Linux-LTS" "Linux-Zen" "Linux-Hardened" "Thoat")
select opt in ${option[*]};
do
case $opt in

"Linux-Hardened")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S linux-hardened --noconfirm
echo
echo
echo "Xong!"

break;;

"Linux-Zen")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S linux-zen --noconfirm
echo
echo
echo "Xong!"

break;;

"Linux-LTS")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S linux-lts --noconfirm
echo
echo
echo "Xong!"

break;;

"Linux")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S linux --noconfirm
echo
echo
echo "Xong!"

break;;

"Thoat")
clear
break;;

esac
done
break;;

"Phan_mem_tien_ich")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Accessories" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("Bleachbit" "Kvantum" "qps" "KSysGuard" "Visual_Studio_Code" "GitHub_Desktop" "Android_Studio" "Java" "wine" "Thoat")
select opt in ${option[*]};
do
case $opt in

"wine")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S wine-git --noconfirm 
echo
echo
echo "Xong!"

break;;


"Java")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S jdk-openjdk 
echo
echo
echo "Xong!"

break;;

"Android_Studio")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S android-studio --noconfirm
echo
echo
echo "Xong!"

break;;

"GitHub_Desktop")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S github-desktop-bin --noconfirm
echo
echo
echo "Xong!"

break;;

"KSysGuard")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S KSysGuard --noconfirm
echo
echo
echo "Xong!"

break;;


"Visual_Studio_Code")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S visual-studio-code-bin --noconfirm
echo
echo
echo "Xong!"

break;;

"qps")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S qps --noconfirm
echo
echo
echo "Xong!"

break;;

"Bleachbit")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S bleachbit --noconfirm
echo
echo
echo "Xong!"

break;;

"Kvantum")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S kvantum-qt5 --noconfirm
echo
echo
echo "Xong!"
break;;

"Thoat")
clear
break;;


esac
done
break;;

"Phan_mem_da_phuong_tien")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Multimedia" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("Spotify" "VLC" "SimpleScreenRecorder" "Kwave" "Thoat")
select opt in ${option[*]};
do
case $opt in


"Thoat")
clear
break;;

"SimpleScreenRecorder")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S simplescreenrecorder --noconfirm
echo
echo
echo "Xong!"

break;;


"Kwave")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S kwave --noconfirm
echo
echo
echo "Xong!"

break;;

"VLC")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S vlc --noconfirm
echo
echo
echo "Xong!"

break;;


"Spotify")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S spotify --noconfirm
echo
echo
echo "Xong!"

break;;
esac
done
break;;

"Phan_mem_sua_anh")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Photo Tools" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("GIMP" "Inkscape" "Krita" "Thoat")
select opt in ${option[*]};
do
case $opt in


"Thoat")
clear
break;;

"Krita")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S krita --noconfirm
echo
echo
echo "Xong!"

break;;


"Inkscape")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S inkscape-git --noconfirm
echo
echo
echo "Xong!"

break;;


"GIMP")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S gimp --noconfirm
echo
echo
echo "Xong!"

break;;


esac
done
break;;

"Phan_mem_sua_van_ban")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Text Editors" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("vim" "nano" "leafpad" "gedit" "Thoat")
select opt in ${option[*]};
do
case $opt in


"Thoat")
clear
break;;

"gedit")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S gedit --noconfirm
echo
echo
echo "Xong!"

break;;

"nano")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S nano --noconfirm
echo
echo
echo "Xong!"

break;;

"vim")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S vim --noconfirm
echo
echo
echo "Xong!"

break;;

"leafpad")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S leafpad --noconfirm
echo
echo
echo "Xong!"

break;;
esac
done
break;;


"Phan_mem_Internet")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Internet Tools" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   " 
echo "===================================================" | lolcat
option=("Cloudflare_WARP" "AnyDesk" "TeamViewer" "qBittorrent" "Microsoft_Edge_Chromium" "Google_Chrome" "Xtreme_Download_Manager" "Thoat")
select opt in ${option[*]};
do
case $opt in

"Google_Chrome")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S google-chrome --noconfirm
echo
echo
echo "Xong!"

break;;


"Thoat")
clear
break;;

"Xtreme_Download_Manager")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S xdman --noconfirm
echo
echo
echo "Xong!"

break;;

"Cloudflare_WARP")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S cloudflare-warp-bin --noconfirm
echo
echo
echo "Dang bat dich vu Cloudflare WARP... vui long cho..."
sudo systemctl enable warp-svc
sudo systemctl start warp-svc
echo
echo "Xin vui long chon y"
echo
warp-cli register
echo
echo "De su dung WARP, hay su dung lenh warp-cli connect."
echo
echo "Xong!"

break;;

"AnyDesk")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S anydesk-bin --noconfirm
echo
echo
echo "Xong!"

break;;

"qBittorrent")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S qbittorrent --noconfirm
echo
echo
echo "Xong!"

break;;


"TeamViewer")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S teamviewer --noconfirm
echo
echo
echo "Xong!"

break;;

"Microsoft_Edge_Chromium")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
yay -S microsoft-edge-dev-bin --noconfirm
echo
echo
echo "Xong!"

break;;

esac
done
break;;


"Trinh_quan_ly_goi")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Package Manager" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("yay" "pamac" "dpkg_(khong_khuyen_khich)" "Thoat")
select opt in ${option[*]};
do
case $opt in


"Thoat")
clear
break;;

"yay")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
echo "Dang cai dat phan mem phu thuoc..."
echo
pacman -S --needed git base-devel
cd ~/Downloads
echo
echo "Dang tai ve file cai dat yay..."
git clone https://aur.archlinux.org/yay.git
cd yay
echo 
echo "Dang cai dat yay..."
makepkg -si
echo
echo "Dang xoa file thua..."
rm -r yay
echo
echo
echo "Xong!"

break;;


"pamac")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
echo "Dang cai dat phan mem phu thuoc..."
echo
pacman -S --needed git base-devel
cd ~/Downloads
echo
echo "Dang tai ve file cai dat yay..."
git clone https://aur.archlinux.org/pamac-aur.git
cd pamac-aur
echo 
echo "Dang cai dat yay..."
makepkg -si
echo
echo "Dang xoa file thua..."
rm -r pamac-aur
echo
echo
echo "Xong!"

break;;


"dpkg")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S dpkg --noconfirm
echo
echo
echo "Xong!"

break;;


esac
done
break;;

"Giao_dien")
clear
figlet -t -f ~/.fonts/cyberlarge.flf "Desktop Environment" | lolcat
echo
echo
echo "===================================================" | lolcat
echo "|    Software Tool - Dang chay tren $distro    "
echo "|-------------------------------------------------"
echo "|    Ban muon cai dat phan mem gi?        "
echo "|    Xin vui long chon lua chon phia ben duoi   "
echo "===================================================" | lolcat
option=("XFCE" "Budgie" "Mate" "GNOME" "Cinnamon" "LXDE" "LXQT" "Thoat")
select opt in ${option[*]};
do
case $opt in


"LXQT")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S lxqt breeze-icons --noconfirm
echo
echo
echo "Xong!"

break;;

"LXDE")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S lxde --noconfirm
echo
echo
echo "Xong!"

break;;

"Cinnamon")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S cinnamon gnome-terminal --noconfirm
echo
echo
echo "Xong!"

break;;

"GNOME")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S gnome --noconfirm
echo
echo
echo "Xong!"

break;;

"Budgie")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S budgie-desktop gnome --noconfirm
echo
echo
echo "Xong!"

break;;

"Mate")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S mate mate-extra --noconfirm
echo
echo
echo "Xong!"

break;;

"XFCE")
clear
echo "Vui long cho... Hay nhap mat khau khi duoc nhac nho!"
echo
sudo pacman -S xfce4 xfce4-goodies --noconfirm
echo
echo
echo "Xong!"

break;;

"Thoat")
clear
break;;



esac
done
break;;

"Thoat")
clear
break;;
esac
done
